spring:
  thymeleaf:
    mode: HTML
    cache: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  database-platform: org.hibernate.dialect.MySQL5Dialect
  messages:
    basename: i18n.messages

logging:
  level:
    root: info
    com.xzq: debug

